/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "这是一个title标题",
  "description": "这是一个description",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/assets/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍，vuepress说明"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "作者"
      }
    ]
  ],
  "pages": [
    {
      "title": "这是一个html页面",
      "frontmatter": {},
      "regularPath": "/about/about.html",
      "relativePath": "about/about.md",
      "key": "v-771d394a",
      "path": "/about/about.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1bccbaa4",
      "path": "/"
    },
    {
      "title": "关于我b",
      "frontmatter": {},
      "regularPath": "/about/bbb.html",
      "relativePath": "about/bbb.md",
      "key": "v-610bbfea",
      "path": "/about/bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我b",
          "slug": "关于我b"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 3,
          "title": "三级标题4",
          "slug": "三级标题4"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-17a1f829",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 3,
          "title": "三级标题4",
          "slug": "三级标题4"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-11370d55",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 3,
          "title": "三级标题4",
          "slug": "三级标题4"
        }
      ]
    },
    {
      "title": "关于我a",
      "frontmatter": {},
      "regularPath": "/css/aaa.html",
      "relativePath": "css/aaa.md",
      "key": "v-4456584a",
      "path": "/css/aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我a",
          "slug": "关于我a"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 3,
          "title": "三级标题4",
          "slug": "三级标题4"
        }
      ]
    },
    {
      "title": "关于我b",
      "frontmatter": {},
      "regularPath": "/css/bbb.html",
      "relativePath": "css/bbb.md",
      "key": "v-748e8a2c",
      "path": "/css/bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我b",
          "slug": "关于我b"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 3,
          "title": "三级标题4",
          "slug": "三级标题4"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "祁子川",
        "link": "http://goodluckweb.top"
      }
    ],
    "sidebar": [
      {
        "title": "关于我",
        "children": [
          "/about/about"
        ],
        "initialOpenGroupIndex": -1
      },
      {
        "title": "css",
        "path": "/css/",
        "children": [
          "/css/aaa",
          "/css/bbb"
        ],
        "initialOpenGroupIndex": -1
      },
      {
        "title": "css2",
        "children": [
          "/css/aaa",
          "/css/bbb"
        ],
        "initialOpenGroupIndex": -1
      },
      {
        "title": "home",
        "children": [
          "",
          ""
        ],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}